// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/compatibility/compatibility.proto

package compatibility

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompatibilityRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TraceId            string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ProductId          string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName        string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Category           string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Quantity           int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price              float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Attributes         map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExistingCategories []string               `protobuf:"bytes,8,rep,name=existing_categories,json=existingCategories,proto3" json:"existing_categories,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompatibilityRequest) Reset() {
	*x = CompatibilityRequest{}
	mi := &file_proto_compatibility_compatibility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompatibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompatibilityRequest) ProtoMessage() {}

func (x *CompatibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compatibility_compatibility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompatibilityRequest.ProtoReflect.Descriptor instead.
func (*CompatibilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_compatibility_compatibility_proto_rawDescGZIP(), []int{0}
}

func (x *CompatibilityRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CompatibilityRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CompatibilityRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CompatibilityRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CompatibilityRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CompatibilityRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CompatibilityRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CompatibilityRequest) GetExistingCategories() []string {
	if x != nil {
		return x.ExistingCategories
	}
	return nil
}

type CompatibilityResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Compatible             bool                   `protobuf:"varint,1,opt,name=compatible,proto3" json:"compatible,omitempty"`
	Message                string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IncompatibleCategories []string               `protobuf:"bytes,3,rep,name=incompatible_categories,json=incompatibleCategories,proto3" json:"incompatible_categories,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CompatibilityResponse) Reset() {
	*x = CompatibilityResponse{}
	mi := &file_proto_compatibility_compatibility_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompatibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompatibilityResponse) ProtoMessage() {}

func (x *CompatibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compatibility_compatibility_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompatibilityResponse.ProtoReflect.Descriptor instead.
func (*CompatibilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_compatibility_compatibility_proto_rawDescGZIP(), []int{1}
}

func (x *CompatibilityResponse) GetCompatible() bool {
	if x != nil {
		return x.Compatible
	}
	return false
}

func (x *CompatibilityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompatibilityResponse) GetIncompatibleCategories() []string {
	if x != nil {
		return x.IncompatibleCategories
	}
	return nil
}

type CategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoriesResponse) Reset() {
	*x = CategoriesResponse{}
	mi := &file_proto_compatibility_compatibility_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriesResponse) ProtoMessage() {}

func (x *CategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compatibility_compatibility_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriesResponse.ProtoReflect.Descriptor instead.
func (*CategoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_compatibility_compatibility_proto_rawDescGZIP(), []int{2}
}

func (x *CategoriesResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_compatibility_compatibility_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compatibility_compatibility_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_compatibility_compatibility_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_compatibility_compatibility_proto protoreflect.FileDescriptor

const file_proto_compatibility_compatibility_proto_rawDesc = "" +
	"\n" +
	"'proto/compatibility/compatibility.proto\x12\rcompatibility\x1a\x1bgoogle/protobuf/empty.proto\"\x86\x03\n" +
	"\x14CompatibilityRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12S\n" +
	"\n" +
	"attributes\x18\a \x03(\v23.compatibility.CompatibilityRequest.AttributesEntryR\n" +
	"attributes\x12/\n" +
	"\x13existing_categories\x18\b \x03(\tR\x12existingCategories\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\x15CompatibilityResponse\x12\x1e\n" +
	"\n" +
	"compatible\x18\x01 \x01(\bR\n" +
	"compatible\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x17incompatible_categories\x18\x03 \x03(\tR\x16incompatibleCategories\"4\n" +
	"\x12CategoriesResponse\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"k\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp2\x89\x02\n" +
	"\x14CompatibilityService\x12_\n" +
	"\x12CheckCompatibility\x12#.compatibility.CompatibilityRequest\x1a$.compatibility.CompatibilityResponse\x12J\n" +
	"\rGetCategories\x12\x16.google.protobuf.Empty\x1a!.compatibility.CategoriesResponse\x12D\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1d.compatibility.HealthResponseB-Z+warehouse_microservices/proto/compatibilityb\x06proto3"

var (
	file_proto_compatibility_compatibility_proto_rawDescOnce sync.Once
	file_proto_compatibility_compatibility_proto_rawDescData []byte
)

func file_proto_compatibility_compatibility_proto_rawDescGZIP() []byte {
	file_proto_compatibility_compatibility_proto_rawDescOnce.Do(func() {
		file_proto_compatibility_compatibility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_compatibility_compatibility_proto_rawDesc), len(file_proto_compatibility_compatibility_proto_rawDesc)))
	})
	return file_proto_compatibility_compatibility_proto_rawDescData
}

var file_proto_compatibility_compatibility_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_compatibility_compatibility_proto_goTypes = []any{
	(*CompatibilityRequest)(nil),  // 0: compatibility.CompatibilityRequest
	(*CompatibilityResponse)(nil), // 1: compatibility.CompatibilityResponse
	(*CategoriesResponse)(nil),    // 2: compatibility.CategoriesResponse
	(*HealthResponse)(nil),        // 3: compatibility.HealthResponse
	nil,                           // 4: compatibility.CompatibilityRequest.AttributesEntry
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_proto_compatibility_compatibility_proto_depIdxs = []int32{
	4, // 0: compatibility.CompatibilityRequest.attributes:type_name -> compatibility.CompatibilityRequest.AttributesEntry
	0, // 1: compatibility.CompatibilityService.CheckCompatibility:input_type -> compatibility.CompatibilityRequest
	5, // 2: compatibility.CompatibilityService.GetCategories:input_type -> google.protobuf.Empty
	5, // 3: compatibility.CompatibilityService.HealthCheck:input_type -> google.protobuf.Empty
	1, // 4: compatibility.CompatibilityService.CheckCompatibility:output_type -> compatibility.CompatibilityResponse
	2, // 5: compatibility.CompatibilityService.GetCategories:output_type -> compatibility.CategoriesResponse
	3, // 6: compatibility.CompatibilityService.HealthCheck:output_type -> compatibility.HealthResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_compatibility_compatibility_proto_init() }
func file_proto_compatibility_compatibility_proto_init() {
	if File_proto_compatibility_compatibility_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_compatibility_compatibility_proto_rawDesc), len(file_proto_compatibility_compatibility_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_compatibility_compatibility_proto_goTypes,
		DependencyIndexes: file_proto_compatibility_compatibility_proto_depIdxs,
		MessageInfos:      file_proto_compatibility_compatibility_proto_msgTypes,
	}.Build()
	File_proto_compatibility_compatibility_proto = out.File
	file_proto_compatibility_compatibility_proto_goTypes = nil
	file_proto_compatibility_compatibility_proto_depIdxs = nil
}
