// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: proto/compatibility.proto

package compatibility

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompatibilityService_CheckCompatibility_FullMethodName = "/compatibility.CompatibilityService/CheckCompatibility"
	CompatibilityService_GetCategories_FullMethodName      = "/compatibility.CompatibilityService/GetCategories"
	CompatibilityService_HealthCheck_FullMethodName        = "/compatibility.CompatibilityService/HealthCheck"
)

// CompatibilityServiceClient is the client API for CompatibilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompatibilityServiceClient interface {
	CheckCompatibility(ctx context.Context, in *CompatibilityRequest, opts ...grpc.CallOption) (*CompatibilityResponse, error)
	GetCategories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CategoriesResponse, error)
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type compatibilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompatibilityServiceClient(cc grpc.ClientConnInterface) CompatibilityServiceClient {
	return &compatibilityServiceClient{cc}
}

func (c *compatibilityServiceClient) CheckCompatibility(ctx context.Context, in *CompatibilityRequest, opts ...grpc.CallOption) (*CompatibilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompatibilityResponse)
	err := c.cc.Invoke(ctx, CompatibilityService_CheckCompatibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compatibilityServiceClient) GetCategories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoriesResponse)
	err := c.cc.Invoke(ctx, CompatibilityService_GetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compatibilityServiceClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CompatibilityService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompatibilityServiceServer is the server API for CompatibilityService service.
// All implementations must embed UnimplementedCompatibilityServiceServer
// for forward compatibility.
type CompatibilityServiceServer interface {
	CheckCompatibility(context.Context, *CompatibilityRequest) (*CompatibilityResponse, error)
	GetCategories(context.Context, *emptypb.Empty) (*CategoriesResponse, error)
	HealthCheck(context.Context, *emptypb.Empty) (*HealthResponse, error)
	mustEmbedUnimplementedCompatibilityServiceServer()
}

// UnimplementedCompatibilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompatibilityServiceServer struct{}

func (UnimplementedCompatibilityServiceServer) CheckCompatibility(context.Context, *CompatibilityRequest) (*CompatibilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckCompatibility not implemented")
}
func (UnimplementedCompatibilityServiceServer) GetCategories(context.Context, *emptypb.Empty) (*CategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedCompatibilityServiceServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCompatibilityServiceServer) mustEmbedUnimplementedCompatibilityServiceServer() {}
func (UnimplementedCompatibilityServiceServer) testEmbeddedByValue()                              {}

// UnsafeCompatibilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompatibilityServiceServer will
// result in compilation errors.
type UnsafeCompatibilityServiceServer interface {
	mustEmbedUnimplementedCompatibilityServiceServer()
}

func RegisterCompatibilityServiceServer(s grpc.ServiceRegistrar, srv CompatibilityServiceServer) {
	// If the following call panics, it indicates UnimplementedCompatibilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompatibilityService_ServiceDesc, srv)
}

func _CompatibilityService_CheckCompatibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompatibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompatibilityServiceServer).CheckCompatibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompatibilityService_CheckCompatibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompatibilityServiceServer).CheckCompatibility(ctx, req.(*CompatibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompatibilityService_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompatibilityServiceServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompatibilityService_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompatibilityServiceServer).GetCategories(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompatibilityService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompatibilityServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompatibilityService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompatibilityServiceServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CompatibilityService_ServiceDesc is the grpc.ServiceDesc for CompatibilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompatibilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compatibility.CompatibilityService",
	HandlerType: (*CompatibilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckCompatibility",
			Handler:    _CompatibilityService_CheckCompatibility_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _CompatibilityService_GetCategories_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CompatibilityService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/compatibility.proto",
}
